export const EXCEL_COLUMNS = {
  FECHA: "FECHA",
  DIRECCION: "DIRECCION",
  NOMBRE_CLIENTE: "NOMBRE CLIENTE",
  SERVICIO_REALIZADO: "SERVICIO REALIZADO",
  VALOR_SERVICIO: "VALOR SERVICIO",
  VALOR_DOMICILIO: "VALOR DOMICILIO",
  VALOR_MATERIALES: "VALOR MATERIALES",
  FORMA_PAGO: "FORMA DE PAGO",
  ESTADO_SERVICIO: "ESTADO DEL SERVICIO",
  IVA: "IVA",
  SUBTOTAL: "SUBTOTAL",
  TOTAL_EMPRESA: "TOTAL EMPRESA",
  VALOR_COMBINADO: "VALOR_COMBINADO"
};

export const FILTER_CRITERIA = {
  FORMA_PAGO_EFECTIVO: "EFECTIVO",
  ESTADO_SERVICIO_VACIO: ""
};

export const PDF_CONFIG = {
  DEFAULT_NAME: "Informe_Servicios.pdf",
  OUTPUT_BASE_FOLDER_NAME: "pdf-relacion-servicios-en-efectivo"
};

export const RESOURCE_PATHS = {
  APP_ICON: "assets/mi_logo.ico",
  HEADER_LOGO: "assets/icono.png",
  EXCEL_ICON: "assets/document_microsoft_excel.png",
  FOLDER_ICON: "assets/carpeta.png",
  CALENDAR_ICON: "assets/calendario.png",
  CALENDAR_ICON_2: "assets/calendario_2.png",
  NOTES_ICON: "assets/document_write.png",
  PROCESS_ICON: "assets/proceso.png",
  PDF_GENERATE_ICON: "assets/icono_pdf.png",
  PDF_OPEN_ICON: "assets/OJO.png",
  TERMINAL_STATUS_ICON: "assets/punto.png",
  TERMINAL_ICON: "assets/konsole.png",
  TRASH_ICON: "assets/papelera.png",
  ARROW_CLICK_ICON: "assets/arrow_click.png",
  NOTE_PAD_ICON: "assets/notepad.png",
  QUIK_ICON: "assets/flechas_circulo.png"
};

export const APP_MESSAGES = {
  APP_TITLE: "Sistema de Relacion de Servicios",
  APP_TITLE_SHORT: "Relaciones de Servicios",
  FILE_SELECT_TITLE: "Seleccionar archivo Excel",
  FILE_TYPES: ["Archivos Excel (*.xlsx *.xls)", "Todos los archivos (*.*)"],
  FILE_SELECTED: "📁 Archivo seleccionado:",
  FILE_LOADED: "Archivo cargado - Listo para procesar",
  PROCESS_START: "⏳ Iniciando procesamiento de datos...",
  NO_RECORDS_FOUND: "No se encontraron registros que cumplan con los criterios",
  RECORDS_FOUND: "Se encontraron {0} registros",
  PROCESS_ERROR: "❌ Error durante el procesamiento:",
  PROCESS_COMPLETE: "✅ Procesamiento completado",
  PDF_NOT_EXIST: "❌ El archivo PDF no existe o la ruta es incorrecta",
  ERROR_TITLE: "Error",
  TERMINAL_TITLE: "Conosola de Procesamiento",
  TERMINAL_ICON_WARNING_NAME: "consola",
  TERMINAL_STATUS_ONLINE: " EN LINEA",
  TERMINAL_STATUS_ICON_WARNING_NAME: "punto de estado",
  BUTTON_CLEAR_TEXT: " Limpiar",
  TRASH_ICON_WARNING_NAME: "papelera",
  WELCOME_MESSAGE_1: "🚀 Sistema de Relacion de Servicios en Efectivo",
  WELCOME_MESSAGE_2: "========================================",
  WELCOME_MESSAGE_3: "💻 Terminal iniciado correctamente",
  WELCOME_MESSAGE_4: "📡 Conexión establecida",
  WELCOME_MESSAGE_5: "🔧 Todos los sistemas operativos",
  WELCOME_MESSAGE_6: "📋 Esperando instrucciones...",

  EXIT_CONFIRM_TITLE: "Salir",
  EXIT_CONFIRM_MESSAGE: "¿Deseas salir de la aplicación?",
  LOADING_APP: "Cargando aplicación...",
  LOADING_SYSTEM: "Iniciando sistema...",
  LOADING_COMPONENTS: "Cargando componentes...",
  LOADING_INTERFACE: "Preparando interfaz...",
  LOADING_SERVICES: "Configurando servicios...",
  READY_TO_WORK: "¡Listo para trabajar!",
  TERMINAL_INIT: "💻 Terminal iniciado correctamente",
  CONNECTION_ESTABLISHED: "📡 Conexión establecida",
  SYSTEMS_OPERATIONAL: "🔧 Todos los sistemas operativos",
  WAITING_INSTRUCTIONS: "📋 Esperando instrucciones...",

  THEME_UPDATED: "🎨 Tema actualizado",
  THEME_CHANGED: "🎨 Tema cambiado a:",
  WARNING_ICON_NOT_FOUND: "Advertencia: No se pudo cargar el icono de {0}: {1}",
  WARNING_LOGO_NOT_FOUND: "Advertencia: No se encontró el logo en '{0}'. Usando logo por defecto.",
  BUTTON_BROWSE_TEXT: "  Examinar",
  FILE_ENTRY_PLACEHOLDER: "Arrastra un archivo aquí o haz clic en Examinar...",
  DATE_RANGE_CARD_TITLE: "Período de Tiempo",
  CALENDAR_ICON_WARNING_NAME: "calendario",
  QUICK_SELECT_LABEL: "Selección Rápida:",
  MONTH_LABEL: "Mes:",
  YEAR_LABEL: "Año:",
  DATE_FROM_LABEL: " Desde:",
  DATE_TO_LABEL: " Hasta:",
  DATE_ENTRY_PLACEHOLDER: "DD/MM/YYYY",
  CALENDAR_POPUP_TITLE: "Seleccionar Fecha",
  CALENDAR_SELECT_BUTTON: "Seleccionar Fecha",
  DATE_PERIOD_UPDATED: "📅 Período actualizado: {0}",
  DATE_SELECTED_FOR: "Fecha seleccionada para {0}: {1}",
  DATE_SELECT_ERROR: "Error al seleccionar fecha del calendario:",
  DATE_UPDATE_MONTH_ERROR: "❌ Error al actualizar fechas por mes:",
  MONTHS_NAMES: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
  DEFAULT_DATE_FORMAT: "DD/MM/YYYY",
  APP_ICON_WARNING_NAME: "aplicación",
  APP_STARTED_SUCCESSFULLY: "🚀 Aplicación iniciada correctamente",
  THEME_UPDATED_LOG: "🎨 Tema actualizado",
  THEME_CHANGED_TO_LOG: "🎨 Tema cambiado a: {0}",
  TERMINAL_CREATE_ERROR: "Error al crear terminal: {0}",

  ERROR_MESSAGE_PREFIX: "❌ ",

  ACTION_CARD_TITLE: "Centro de Acciones",
  PDF_NAME_LABEL: "Nombre del informe:",
  PDF_NAME_PLACEHOLDER: "Escribe el nombre del archivo PDF...",
  BUTTON_PROCESS_TEXT: " Procesar Datos",
  BUTTON_PROCESSING_TEXT: "⏳ Procesando...",
  BUTTON_PROCESS_PENDIENTES_TEXT: " Procesar Pendientes",
  BUTTON_GENERATE_PDF_TEXT: " Generar PDF",
  BUTTON_OPEN_PDF_TEXT: " Abrir PDF",
  BUTTON_PENDIENTES_TEXT: " Pendientes",
  ACTION_CARD_ICON_NAME: "acciones",
  PROCESS_ICON_WARNING_NAME: "proceso",
  PDF_GENERATE_ICON_WARNING_NAME: "icono_pdf",
  PDF_OPEN_ICON_WARNING_NAME: "OJO",
  EXCEL_ICON_WARNING_NAME: "excel",
  FOLDER_ICON_WARNING_NAME: "carpeta",
  HEADER_SUBTITLE: "Genera informes de servicios pagados con tecnología avanzada",
  HEADER_STATUS_LABEL: "Estado:",
  HEADER_STATUS_NORMAL: "Normal",
  MENU_BUTTON_TEXT: "☰",
  HEADER_ICON_WARNING_NAME: "encabezado",
  MENU_OPTIONS_TITLE: "Opciones",
  THEME_LABEL: "Tema:",
  THEME_VALUES_CLARO: "Claro",
  THEME_VALUES_OSCURO: "Oscuro",
  THEME_VALUES_SISTEMA: "Sistema",
  MENU_CLOSE_BUTTON: "Cerrar",
  NOTES_CARD_TITLE: "Notas del Informe",
  NOTES_ICON_WARNING_NAME: "notas",
  NOTES_ENTRY_PLACEHOLDER: "Escribe tus notas aquí...",
  WORK_MODE_SERVICES: "Relación de Servicios",
  WORK_MODE_PENDING: "Pagos Pendientes"
}; 